[package]
name = "fdlimit"
version = "0.1.4"
authors = ["Parity Technologies<admin@parity.io>"]
license = "Apache-2.0"
description = "Utility crate for raising file descriptors limit for OSX and Linux"
repository = "https://github.com/paritytech/fdlimit"

[dependencies]
libc = "0.2"